on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest

    steps:
     - name: set api key
       run: echo "API_KEY=12345" >> $GITHUB_ENV
     - name: use api key
       run: |
         echo "::add-mask::$API_KEY"
         echo "using api key $API_KEY"
