on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest

    steps:
      - name: set api key
        run: echo "API_KEY=12345" >> $GITHUB_ENV
      - name: uses api key
        run: echo "using API key $API_KEY"
