on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest

    steps:
     - name: check if file exist or no
       run: |
         if [ -f "config.yml" ]; then
           echo "::debug:: file exist"
         else
           echo "::error:: file not exist"
         fi
