name: First Workflow
on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: print a welcome message
        run: echo "Welcome to our first GitHub Actions Workflow!"
      - name: Checkout
        uses: actions/checkout@v7.0.0
      - name: list repos files
        run: ls -la
