name: workflow
on:
    push:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4.2.2

            - name: Run test
              run: |
                cd src/
                npm test